org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)
forge_version=47.2.32
forge_version_range=[46,)
loader_version_range=[46,)
mapping_channel=official
mapping_version=1.20.1

mod_id=luckytntmod
mod_name=Lucky TNT Mod
mod_license=All Rights Reserved
mod_version=2.4
mod_group_id=luckytnt.luckytntmod
mod_authors=SlimingHD, Fleshcrafter
mod_description=Lucky TNT adds tons of new TNT to destroy your world with!